# Generated by Django 5.0.1 on 2024-01-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(default=0, verbose_name='Общая стоимость')),
                ('items', models.ManyToManyField(related_name='orders', to='payments.item', verbose_name='Товары')),
            ],
        ),
    ]
